export const SEARCH_ENTITIES = 'SEARCH_ENTITIES';
export const SEARCH_ASYNC_ENTITIES = 'SEARCH_ASYNC_ENTITIES';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_MODAL = 'OPEN_MODAL';
export const IS_LOADING = 'IS_LOADING';
